version: 1.1.{build}-appveyor
image: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
configuration:
- Debug
- Release
before_build:
  - cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: nuget pack CSCore\CSCore.csproj -Prop Configuration=%CONFIGURATION% -Symbols
  - cmd: nuget pack CSCore.OSX\CSCore.OSX.csproj -Prop Configuration=%CONFIGURATION% -Symbols -IncludeReferencedProjects
artifacts:
  - path: '**\*CSCore*.nupkg'
test: off